project:
  type: website
  output-dir: docs

website:
  favicon: "assets/favicon.ico"
  title: "JuliaHealth"
  image: "assets/images/logo.png"
  image-alt: "JuliaHub Logo"
  announcement:
    icon: megaphone
    dismissable: true
    content: "[**JuliaCon 2026**](https://juliacon.org/2026/): Submit your talks for the Health Mini-Symposium [here](https://pretalx.com/juliacon-2026/talk/NR9PGW/)!"
    type: primary
    position: above-navbar
  navbar:
    logo: "assets/images/logo.png"
    logo-alt: "JuliaHub Logo"
    left:
      - href: index.qmd
        text: Home
        icon: house-door
      - text: About Us
        icon: info-circle
        menu:
          - href: pages/who_we_are.qmd
            text: Who We Are
            icon: people
          - href: pages/research.qmd
            text: Research
            icon: journal-text
          - href: pages/connect_with_us.qmd
            text: Connect With Us
            icon: chat-heart
      - href: pages/packages.qmd
        text: Packages
        icon: boxes
      - href: JuliaHealthBlog/index.qmd
        text: Blogs
        icon: journal-richtext
      - text: Contributing
        icon: heart
        menu:
          - href: pages/contributing.qmd
            text: Migrating your package to JuliaHealth
            icon: arrow-left-right
      - text: "More"
        menu:
          - href: pages/meeting_notes.qmd
            text: Meetings Notes
            icon: card-text
          - href: pages/related_organizations.qmd
            text: Related Organizations
            icon: buildings
  page-footer:
    left:
      - text: "Copyright 2024-25, JuliaHealth."
        icon: c-circle
    right:
      - href: https://github.com/JuliaHealth/JuliaHealthBlog
        text: Report Issue

bread-crumbs: true

format:
  html:
    theme:
      light: 
        - cosmo
        - brand
    css: styles.css
    toc: true
