<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Anvika Singhal">
<meta name="dcterms.date" content="2026-08-20">
<meta name="description" content="Bringing GPU-accelerated MRI simulation to Python through Julia interop, precompilation, and a bidirectional JAX autodiff proof-of-concept.">

<title>GSoC ’26: komamripy - Python Wrapper for KomaMRI – JuliaHealth</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../assets/favicon.ico" rel="icon">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-54501c6f4d8fcbe8b6dd67a2cc408366.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <div id="quarto-announcement" data-announcement-id="fdcc6ba07ee5c4e92eba5725cbff0470" class="alert alert-primary hidden"><i class="bi bi-megaphone quarto-announcement-icon"></i><div class="quarto-announcement-content">
<p><a href="https://juliacon.org/2026/"><strong>JuliaCon 2026</strong></a>: Submit your talks for the Health Mini-Symposium <a href="https://pretalx.com/juliacon-2026/talk/NR9PGW/">here</a>!</p>
</div><i class="bi bi-x-lg quarto-announcement-action"></i></div>
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../assets/images/logo.png" alt="JuliaHub Logo" class="navbar-logo light-content">
    <img src="../../../assets/images/logo.png" alt="JuliaHub Logo" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">JuliaHealth</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> <i class="bi bi-house-door" role="img">
</i> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../pages/packages.html"> <i class="bi bi-boxes" role="img">
</i> 
<span class="menu-text">Packages</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../JuliaHealthBlog/index.html"> <i class="bi bi-journal-richtext" role="img">
</i> 
<span class="menu-text">Blogs</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ecosystem" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-diagram-3" role="img">
</i> 
 <span class="menu-text">Ecosystem</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ecosystem">    
        <li>
    <a class="dropdown-item" href="../../../pages/ecosystem_health.html"><i class="bi bi-activity" role="img">
</i> 
 <span class="dropdown-text">Ecosystem Health</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../../pages/connect_with_us.html"> <i class="bi bi-chat-heart" role="img">
</i> 
<span class="menu-text">Connect With Us</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">More</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more">    
        <li>
    <a class="dropdown-item" href="../../../pages/meeting_notes.html"><i class="bi bi-card-text" role="img">
</i> 
 <span class="dropdown-text">Meetings Notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../pages/related_organizations.html"><i class="bi bi-buildings" role="img">
</i> 
 <span class="dropdown-text">Related Organizations</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#hello" id="toc-hello" class="nav-link active" data-scroll-target="#hello">Hello!</a></li>
  <li><a href="#what-is-komamri" id="toc-what-is-komamri" class="nav-link" data-scroll-target="#what-is-komamri">What is KomaMRI?</a></li>
  <li><a href="#why-komamripy" id="toc-why-komamripy" class="nav-link" data-scroll-target="#why-komamripy">Why komamripy?</a></li>
  <li><a href="#goal-1-a-pip-installable-package-built-to-modern-python-standards" id="toc-goal-1-a-pip-installable-package-built-to-modern-python-standards" class="nav-link" data-scroll-target="#goal-1-a-pip-installable-package-built-to-modern-python-standards">Goal 1: A pip-installable Package, Built to Modern Python Standards</a>
  <ul class="collapse">
  <li><a href="#package-structure" id="toc-package-structure" class="nav-link" data-scroll-target="#package-structure">Package Structure</a></li>
  <li><a href="#api-design" id="toc-api-design" class="nav-link" data-scroll-target="#api-design">API Design</a></li>
  <li><a href="#getting-ci-working" id="toc-getting-ci-working" class="nav-link" data-scroll-target="#getting-ci-working">Getting CI Working</a></li>
  <li><a href="#automated-release-pipeline" id="toc-automated-release-pipeline" class="nav-link" data-scroll-target="#automated-release-pipeline">Automated Release Pipeline</a></li>
  </ul></li>
  <li><a href="#goal-2-precompilation-to-reduce-first-use-latency" id="toc-goal-2-precompilation-to-reduce-first-use-latency" class="nav-link" data-scroll-target="#goal-2-precompilation-to-reduce-first-use-latency">Goal 2: Precompilation to reduce First-Use Latency</a>
  <ul class="collapse">
  <li><a href="#benchmarks" id="toc-benchmarks" class="nav-link" data-scroll-target="#benchmarks">Benchmarks</a></li>
  </ul></li>
  <li><a href="#goal-3-gpu-backend-selection" id="toc-goal-3-gpu-backend-selection" class="nav-link" data-scroll-target="#goal-3-gpu-backend-selection">Goal 3: GPU Backend Selection</a></li>
  <li><a href="#goal-2-continued-examples-and-feature-tests" id="toc-goal-2-continued-examples-and-feature-tests" class="nav-link" data-scroll-target="#goal-2-continued-examples-and-feature-tests">Goal 2 (continued): Examples and Feature Tests</a></li>
  <li><a href="#goal-4-jax-integration---research-and-proof-of-concept" id="toc-goal-4-jax-integration---research-and-proof-of-concept" class="nav-link" data-scroll-target="#goal-4-jax-integration---research-and-proof-of-concept">Goal 4: JAX Integration - Research and Proof of Concept</a></li>
  <li><a href="#conclusions-and-future-work" id="toc-conclusions-and-future-work" class="nav-link" data-scroll-target="#conclusions-and-future-work">Conclusions and Future Work</a></li>
  <li><a href="#acknowledgements" id="toc-acknowledgements" class="nav-link" data-scroll-target="#acknowledgements">Acknowledgements</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">GSoC ’26: <code>komamripy</code> - Python Wrapper for KomaMRI</h1>
  <div class="quarto-categories">
    <div class="quarto-category">gsoc</div>
    <div class="quarto-category">mri</div>
    <div class="quarto-category">python</div>
    <div class="quarto-category">julia</div>
    <div class="quarto-category">gpu</div>
    <div class="quarto-category">simulation</div>
  </div>
  </div>

<div>
  <div class="description">
    Bringing GPU-accelerated MRI simulation to Python through Julia interop, precompilation, and a bidirectional JAX autodiff proof-of-concept.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Anvika Singhal </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 20, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="hello" class="level1">
<h1>Hello!</h1>
<p>I am Anvika, an undergrad at Caltech studying electrical engineering. I’m particularly interested in biomedical engineering, physics, high-performance computing, and where they intersect. This summer, I participated in Google Summer of Code 2026 under JuliaHealth.</p>
<p>I developed <a href="https://github.com/JuliaHealth/komamripy" target="_blank" style="color: inherit; text-decoration: none;"><code style="color: #7a1eba;">komamripy</code></a>: a Python wrapper for KomaMRI.jl, a GPU-accelerated MRI simulation platform.</p>
<blockquote class="blockquote">
<p>The <code>komamripy</code> package lives at <a href="https://github.com/JuliaHealth/komamripy"><strong>JuliaHealth/komamripy</strong></a> and <a href="https://pypi.org/project/komamripy/">PyPI</a>.<br>
You can connect with me on <a href="https://github.com/anvika-singhal">GitHub</a> or <a href="https://www.linkedin.com/in/anvika-singhal/">LinkedIn</a>.</p>
</blockquote>
<p>In this post, I’ll summarize everything I accomplished over the course of this program. I would also like to go over some motivations behind key decisions, things I learned, and the parts that are still in progress.</p>
</section>
<section id="what-is-komamri" class="level1">
<h1>What is KomaMRI?</h1>
<p><a href="https://github.com/JuliaHealth/KomaMRI.jl">KomaMRI.jl</a> is an open-source Julia package for simulating Magnetic Resonance Imaging (MRI) acquisitions.</p>
<p>KomaMRI generates simulated raw MRI data by numerically solving the Bloch equations that describe how the magnetization of a nucleus changes when magnetic fields are applied. Researchers can use it to test pulse sequences/reconstruction algorithms that they have designed. Importantly, it is not dependent on access to a physical scanner, a possibly time-consuming and expensive limitation. The package also supports GPU backend acceleration (CUDA, AMDGPU, Metal, and oneAPI) and comes with a graphical user interface in addition to a flexible programmatic API.</p>
</section>
<section id="why-komamripy" class="level1">
<h1>Why komamripy?</h1>
<p>KomaMRI.jl is built entirely in Julia. However, most modern scientific computing and machine learning workflows are built in Python using tools like NumPy, JAX, and PyTorch. It is not currently convenient or accessible to integrate KomaMRI’s strength in simulation with a Python pipeline.</p>
<p><code>komamripy</code> bridges this gap between Julia and Python by exposing KomaMRI’s core API to Python users through a thin wrapper. This makes it so that a simulation that would normally look like this in Julia:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode julia code-with-copy"><code class="sourceCode julia"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Julia</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">KomaMRI</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">using</span> <span class="bu">CUDA</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>sys <span class="op">=</span> <span class="fu">Scanner</span>()</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>obj <span class="op">=</span> <span class="fu">brain_phantom2D</span>()</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>seq <span class="op">=</span> PulseDesigner.<span class="fu">EPI_example</span>()</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>raw <span class="op">=</span> <span class="fu">simulate</span>(obj, seq, sys)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>can be run like this in Python:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Python</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> komamripy <span class="im">as</span> km</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>km.load_cuda()</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>sys <span class="op">=</span> km.Scanner()</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>obj <span class="op">=</span> km.brain_phantom2D()</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>seq <span class="op">=</span> km.PulseDesigner.EPI_example()</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>raw <span class="op">=</span> km.simulate(obj, seq, sys)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The syntax is mirrored almost exactly 1:1 making usage as straightforward as possible.</p>
</section>
<section id="goal-1-a-pip-installable-package-built-to-modern-python-standards" class="level1">
<h1>Goal 1: A pip-installable Package, Built to Modern Python Standards</h1>
<p>The first goal was to ship an installable Python package built to best Python practices.</p>
<blockquote class="blockquote">
<p><a href="https://github.com/JuliaHealth/komamripy/pull/1">JuliaHealth/komamripy/pull/1</a><br>
<a href="https://github.com/JuliaHealth/komamripy/pull/3">JuliaHealth/komamripy/pull/3</a><br>
<a href="https://github.com/JuliaHealth/komamripy/pull/4">JuliaHealth/komamripy/pull/4</a><br>
<a href="https://github.com/JuliaHealth/komamripy/pull/5">JuliaHealth/komamripy/pull/5</a><br>
<a href="https://github.com/JuliaHealth/komamripy/pull/10">JuliaHealth/komamripy/pull/10</a><br>
<a href="https://github.com/JuliaHealth/komamripy/pull/14">JuliaHealth/komamripy/pull/14</a></p>
</blockquote>
<section id="package-structure" class="level2">
<h2 class="anchored" data-anchor-id="package-structure">Package Structure</h2>
<pre><code>komamripy/
├── .github/
│   ├── dependabot.yml
│   └── workflows/
│       ├── ci.yml                   # Test matrix: Linux, macOS, Windows × Python 3.11, 3.14
│       ├── publish.yml              # Build and publish to PyPI triggered by tag push
│       ├── tag_release.yml          # Create git tag when auto-bump PR is merged
│       └── update_deps.yml          # Weekly: resolve KomaMRI versions, open auto-bump PR
├── examples/
│   ├── basic_simulation.py          # End-to-end EPI simulation with brain phantom
│   ├── custom_phantom_creation.py   # Build phantom from NumPy arrays, save/load, simulate
│   ├── gpu_backend_selection.py     # Simple simulation with GPU backend loaded
│   ├── motion_artifact.py           # Rigid-body motion simulation and artifact comparison
│   └── pypulseq_composability.py    # Pulseq sequence full round-trip I/O
├── scripts/
│   └── update_deps.py               # Resolve KomaMRI versions, update juliapkg.json
├── src/
│   └── komamripy/
│       ├── __init__.py              # Mirror-based API: forwards attribute access to KomaMRI
│       ├── _backends.py             # Load GPU backend functionality
│       ├── _session.py              # Lazy Julia session: loads Julia and KomaMRI on first use
│       └── juliapkg.json            # Pinned Julia and KomaMRI dependency declarations
├── tests/
│   ├── smoke_test.py                # Fast checks that don't require a Julia session
│   └── test_integration_examples.py # End-to-end tests, one per example script
├── pyproject.toml                   # Package metadata, dependencies, uv and ruff configuration
└── README.md</code></pre>
<p>A modern Python package has a standard set of tools, and <code>komamripy</code> uses all of them:</p>
<ul>
<li><code>pyproject.toml</code> - single config file for the entire package with metadata, dependencies, build system, and linting rules all in one place.</li>
<li><code>uv</code> - fast, reproducible environment + dependency management. Consolidate pip, virtualenv, and pip-tools into a single tool.</li>
<li><code>ruff</code> - linting and formatting. Enforces consistent code style and catches common errors on every commit.</li>
<li>GitHub Actions - automated testing on every pull request across Linux, macOS, and Windows, automated package updates and deployment.</li>
</ul>
</section>
<section id="api-design" class="level2">
<h2 class="anchored" data-anchor-id="api-design">API Design</h2>
<p><code>komamripy</code> is centered around a mirror-based API which is implemented in <code>__init__.py</code>. Specifically, a module-level <code>__getattr__</code> pushes any attribute access directly to the Julia-side <code>KomaMRI</code> namespace using JuliaCall which is what enables the transparent Julia-Python translation. Also, subpackages such as <code>KomaMRICore</code> and <code>PulseDesigner</code> are resolved through a <code>seval</code> fallback.</p>
<p>The Julia session itself is built to be lazy. This means that Julia and KomaMRI are only loaded on first use so importing <code>komamripy</code> does not have the Julia startup cost. Instead, the cost only present when a function is actually called.</p>
<p>Julia dependencies, specifically KomaMRI and its subpackages, are declared in <code>juliapkg.json</code> and installed automatically by JuliaCall on first import. Users do not need any seperate Julia install nor do they need to manage their own Julia environment, making the package accesible to users without any Julia experience whatsoever.</p>
</section>
<section id="getting-ci-working" class="level2">
<h2 class="anchored" data-anchor-id="getting-ci-working">Getting CI Working</h2>
<p>Getting thorough tests to pass reliably across all platforms ended up being a technically tricky part of this goal. One key issue ended up being Julia version selection. JuliaCall would select the runner’s preinstalled Julia on CI, but on some platforms this hit OpenSSL and embed-path failures. The fix was to pin the Julia version declaratively in <code>juliapkg.json</code> (to <code>~1.10</code> LTS), mimicing the approach that other Julia-from-Python wrappers like PySR use. Other than CI, this pin also serves to protect end users.</p>
<p>In the end, Python support was set to be <code>&gt;=3.11</code> after running a full diagnostic matrix. Python 3.10 fails on Windows with uv-managed Python due to OpenSSL issues, while 3.11 through 3.14 pass across all platforms. The final CI matrix runs Python 3.11 and 3.14 on Ubuntu, macOS, and Windows plus a lint job for a total 7 jobs per run.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="passing_CI.png" class="img-fluid figure-img"></p>
<figcaption>A passing CI run across all platforms and Python versions.</figcaption>
</figure>
</div>
</section>
<section id="automated-release-pipeline" class="level2">
<h2 class="anchored" data-anchor-id="automated-release-pipeline">Automated Release Pipeline</h2>
<p>Keeping Julia dependency versions up to date manually is error-prone and time consuming. <code>komamripy</code> has a fully automated weekly pipeline:</p>
<ol type="1">
<li>A scheduled GitHub Action runs <code>scripts/update_deps.py</code> which uses Julia’s Pkg resolver to check for new compatible versions of KomaMRI and its subpackages.</li>
<li>If available versions are different from those currently pinned in <code>komamripy</code>, it opens a PR titled <code>[auto] Bump to version X.X.X</code> with the changes to the pins and internal version declaration.</li>
<li>Once CI passes, the PR auto-merges. If CI fails, the process holds at PR for review.</li>
<li>A separate workflow detects the merge, creates a git tag, and pushes it.</li>
<li>The tag push triggers the publish workflow which builds and publishes to PyPI.</li>
</ol>
<p>The result is that <code>komamripy</code> tracks KomaMRI releases automatically with no manual steps needed on the happy path.</p>
</section>
</section>
<section id="goal-2-precompilation-to-reduce-first-use-latency" class="level1">
<h1>Goal 2: Precompilation to reduce First-Use Latency</h1>
<p>Julia has a known first call latency since the first time a function is called in a fresh Julia session, it must be compiled from source. For a package like KomaMRI, this can mean waiting tens of seconds before the first simulation runs. This latency trickles down to <code>komamripy</code> as well.</p>
<p>The fix is precompilation using <a href="https://github.com/JuliaLang/PrecompileTools.jl">PrecompileTools.jl</a>. During package installation, Julia compiles the specified workloads and caches the bytecode. Loads that follow show significantly reduced compilation and run time.</p>
<blockquote class="blockquote">
<p><a href="https://github.com/JuliaHealth/KomaMRI.jl/pull/820">JuliaHealth/KomaMRI.jl/pull/820</a><br>
<a href="https://github.com/JuliaHealth/KomaMRI.jl/pull/929">JuliaHealth/KomaMRI.jl/pull/929</a></p>
</blockquote>
<p>I added precompilation workloads across three KomaMRI subpackages:</p>
<ul>
<li><strong>KomaMRIBase</strong>: <code>Scanner</code>, <code>Phantom</code>, <code>Sequence</code> (with all event types: RF, gradients, ADC, Delay), motion attachment, <code>PulseDesigner.EPI_example</code>, <code>brain_phantom2D</code></li>
<li><strong>KomaMRICore</strong>: <code>simulate()</code> with all simulation methods (Bloch, BlochDict), Float32 and Float64 variants, all export formats (mat, raw), sequence discretization</li>
<li><strong>KomaMRIFiles</strong>: Pulseq sequence read/write, phantom file I/O (read/write roundtrip)</li>
</ul>
<p>The functions that would most benefit from precompilation were chosen by looking at how frequency they appear across the KomaMRI docs, a proxy for how often each function in used in typical user workflows:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Function</th>
<th>Docs mentions</th>
<th>Precompiled</th>
<th>Subpackage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Sequence</code></td>
<td>178</td>
<td>all event types</td>
<td>Base</td>
</tr>
<tr class="even">
<td><code>Phantom</code></td>
<td>110</td>
<td>built-in + custom</td>
<td>Base</td>
</tr>
<tr class="odd">
<td><code>PulseDesigner</code></td>
<td>58</td>
<td><code>EPI_example</code></td>
<td>Base</td>
</tr>
<tr class="even">
<td><code>Scanner</code></td>
<td>38</td>
<td>constructor</td>
<td>Base</td>
</tr>
<tr class="odd">
<td><code>simulate</code></td>
<td>22</td>
<td>all methods/types</td>
<td>Core</td>
</tr>
<tr class="even">
<td><code>write_seq</code></td>
<td>10</td>
<td>with all events</td>
<td>Files</td>
</tr>
<tr class="odd">
<td><code>read_seq</code></td>
<td>7</td>
<td>with all events</td>
<td>Files</td>
</tr>
<tr class="even">
<td><code>EPI_example</code></td>
<td>9</td>
<td>via PulseDesigner</td>
<td>Base</td>
</tr>
<tr class="odd">
<td><code>brain_phantom2D</code></td>
<td>8</td>
<td>built-in</td>
<td>Core</td>
</tr>
<tr class="even">
<td><code>read/write_phantom</code></td>
<td>8</td>
<td>I/O roundtrip</td>
<td>Files</td>
</tr>
</tbody>
</table>
<p>Workloads use a simple 1-2 spin phantom to keep precompilation relatively fast. They are placed in the subpackage that defines each function instead of being centralized in the top-level KomaMRI.jl. This helps make sure that they have the correct dependency order (Base -&gt; Core -&gt; Files).</p>
<section id="benchmarks" class="level2">
<h2 class="anchored" data-anchor-id="benchmarks">Benchmarks</h2>
<p>The script used for benchmarking runs each of the 10 functions 10x in separate Python subprocesses so that every run has the full Julia cold-start cost. Average run times are then compared before and after precompilation.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="komamripy_benchmark.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Two bar charts side by side. Left chart: CPU precompilation benchmark, comparing v0.0.6 (before) and v0.0.7 (after) average times in seconds for each of the 10 benchmarked functions. Right chart: GPU precompilation benchmark, comparing v0.0.9 (before) and v0.0.10 (after). Both charts: x-axis = function name (Scanner, brain_phantom2D, EPI_example, discretize, simulate, Phantom, write_phantom, read_phantom, …), y-axis = time in seconds, two grouped bars per function.</figcaption>
</figure>
</div>
<blockquote class="blockquote">
<p>NOTE: the precompilation workload focuses on the most common sequence types, but real pulse sequences are highly dynamic. It is probable that some combinations are not addressed by precompilation. A good portion of <code>simulate()</code> time may also be spent in <code>discretize()</code>. This may be an area for future optimization.</p>
</blockquote>
</section>
</section>
<section id="goal-3-gpu-backend-selection" class="level1">
<h1>Goal 3: GPU Backend Selection</h1>
<p>In KomaMRI.jl, GPU backends are not loaded by default. A user can enable GPU acceleration by explicitly loading a backend package in Julia. For example, <code>using CUDA</code> alongside <code>using KomaMRI</code> triggers a package extension that defines methods like <code>gpu()</code> for converting arrays to device-specific types (<code>CuArray</code> for CUDA, <code>ROCArray</code> for AMDGPU, etc.). The actual simulation code is not GPU dependent and will run unedited, no matter the backend.</p>
<blockquote class="blockquote">
<p><a href="https://github.com/JuliaHealth/komamripy/pull/23">JuliaHealth/komamripy/pull/23</a></p>
</blockquote>
<p><code>komamripy</code> mirrors this system exactly in <code>_backends.py</code> by creating a function to expose each backend:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> komamripy <span class="im">as</span> km</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load a GPU backend before simulating</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>km.load_cuda()    <span class="co"># equivalent to `using CUDA` in Julia</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># km.load_metal()   # Apple Silicon</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># km.load_amdgpu()  # AMD GPUs</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># km.load_oneapi()  # Intel GPUs</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulation runs on GPU automatically</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>raw <span class="op">=</span> km.simulate(obj, seq, sys)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Each function calls <code>jl.seval()</code> to load the corresponding Julia package into the active Julia session enabling GPU dispatch. No other management is needed on either the Python or Julia side, again keeping the user experience streamlined.</p>
<p>The <code>gpu_backend_selection.py</code> lets users try simulations run on CPU by default (no backend loading), and that switching backends only involves a single import change and no changes to the following code.</p>
</section>
<section id="goal-2-continued-examples-and-feature-tests" class="level1">
<h1>Goal 2 (continued): Examples and Feature Tests</h1>
<p>Alongside the basic package scaffolding and functionality, a number of end-to-end examples were added to demonstrate the core <code>komamripy</code> workflows.</p>
<blockquote class="blockquote">
<p><a href="https://github.com/JuliaHealth/komamripy/pull/12">JuliaHealth/komamripy/pull/12</a></p>
</blockquote>
<p>These examples are as follows:</p>
<ul>
<li><code>basic_simulation.py</code>: Run a simple EPI simulation with the built-in brain phantom, returning a NumPy signal array.</li>
<li><code>pypulseq_composability.py</code>: Create a KomaMRI-compatible sequence with pypulseq, write it to <code>.seq</code> format, read it back with KomaMRI, and verify the round-trip.</li>
<li><code>custom_phantom_creation.py</code>: Build a custom 2-tissue phantom from NumPy arrays, save and load <code>.phantom</code> files, combine phantoms, and simulate.</li>
<li><code>motion_artifact.py</code>: Attach rigid-body motion to a phantom and simulate w/ and w/o motion, showing how motion-induced artifacts turn up in the raw signal.</li>
</ul>
<p>Each example has a linked integration test in <code>tests/test_integration_examples.py</code> that checks that it runs without errors and generates the expected output.</p>
</section>
<section id="goal-4-jax-integration---research-and-proof-of-concept" class="level1">
<h1>Goal 4: JAX Integration - Research and Proof of Concept</h1>
<p>The final goal was to explore differentiable MRI simulation from Pytho. Specifically, we were hoping to determine whether KomaMRI’s Julia-based autodiff capabilities could be exposed to JAX, allowing gradient-based RF pulse optimization in Python.</p>
<p>To begin, this necesitated researching bidirectional interoperability between JAX and Julia using <a href="https://github.com/EnzymeAD/Reactant.jl">Reactant.jl</a>, which can compile Julia code to <a href="https://github.com/openxla/stablehlo">StableHLO</a> which is the same intermediate representation JAX uses internally. A proof-of-concept repository (<a href="https://github.com/anvika-singhal/reactant-jax-poc">reactant-jax-poc</a>) was built to clearly validate and demonstrate three possible branches of interoperability:</p>
<blockquote class="blockquote">
<p><a href="https://github.com/anvika-singhal/reactant-jax-poc">anvika-singhal/reactant-jax-poc</a></p>
</blockquote>
<p><strong>Direction 1: Julia -&gt; JAX</strong></p>
<p>A Julia function is compiled to StableHLO via Reactant.jl, then executed and differentiated from Python using EnzymeJAX’s <code>hlo_call</code>. This direction works and produces correct gradients. There is one known issue in that Reactant currently emits <code>tf.aliasing_output</code> annotations in the StableHLO that break EnzymeJAX’s VJP. The current workaround patches the MLIR string before calling <code>hlo_call</code>, which would be fragile for more complex functions. This needs a fix upstream in Reactant.jl or Enzyme-JAX or something similar.</p>
<p><strong>Direction 2: JAX -&gt; Julia</strong></p>
<p>A JAX function defined fully in Python is called and differentiated from Julia via <code>Reactant.@jit</code> and <code>Enzyme.gradient</code>. This direction works cleanly and correct gradients were verified against known values.</p>
<p><strong>Direction 3: JAX MLP training loop in Julia</strong></p>
<p>A 2-layer MLP defined in JAX (input:4 → hidden:8 tanh → output:2) is trained from Julia using Enzyme gradients. The gradient computation and weight update are pushed into a single <code>@compiled</code> function. This means that weights remain on-device, and the loss was demonstrated to decrease correctly over training steps:</p>
<pre><code>Step  1 loss = 0.443342
Step  5 loss = 0.365651
Step 10 loss = 0.283788
Step 15 loss = 0.216205
Step 20 loss = 0.161262</code></pre>
<p>The infrastructure demonstrated here is exciting! If the <code>tf.aliasing_output</code> issue is resolved, the full bidirectional autodiff channel between JAX and KomaMRI would be very close to complete. This proof-of-concept makes it clear that the approach is sound. One platform cavaet is that Linux x86_64 or macOS ARM64 is currently required due to <code>enzyme-ad</code> wheel availability.</p>
</section>
<section id="conclusions-and-future-work" class="level1">
<h1>Conclusions and Future Work</h1>
<p>Over the course of GSoC 2026, <code>komamripy</code> went from just an idea to a pip-installable Python package with:</p>
<ul>
<li>A mirror-based Python API that exposes the KomaMRI Julia API cleanly</li>
<li>Cross-platform CI (Linux, macOS, Windows) with automated weekly dependency updates and PyPI publishing</li>
<li>CPU and GPU precompilation in KomaMRI.jl, measurably reducing first-use latency in <code>komamripy</code></li>
<li>GPU backend selection mirroring KomaMRI.jl’s package extension system</li>
<li>End-to-end examples covering simulation, Pulseq I/O, custom phantoms, and motion artifacts</li>
<li>A proof-of-concept for bidirectional JAX-Julia automatic differentiation</li>
</ul>
<p>Remaining work includes resolving the <code>tf.aliasing_output</code> issue in Direction 1 of the JAX integration, building the full differentiable RF optimization example once that is fixed, and possibly exploring multi-GPU simulation examples.</p>
</section>
<section id="acknowledgements" class="level1">
<h1>Acknowledgements</h1>
<p>Thank you to my mentor Carlos Castillo Passi, who provided neverending patience and guidance throughout the summer. I would also like to thank Daniel Ennis and Jakub Mitura for their support.</p>


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" id="quarto-citation"><h2 class="anchored quarto-appendix-heading">Citation</h2><div><div class="quarto-appendix-secondary-label">BibTeX citation:</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{singhal2026,
  author = {Singhal, Anvika},
  title = {GSoC ’26: `Komamripy` - {Python} {Wrapper} for {KomaMRI}},
  date = {2026-08-20},
  langid = {en}
}
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">For attribution, please cite this work as:</div><div id="ref-singhal2026" class="csl-entry quarto-appendix-citeas" role="listitem">
Singhal, Anvika. 2026. <span>“GSoC ’26: `Komamripy` - Python Wrapper for
KomaMRI.”</span> August 20.
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<script src="https://utteranc.es/client.js" repo="JuliaHealth/JuliaHealthBlog" issue-term="title" theme="github-dark" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
      <i class="bi bi-c-circle" role="img">
</i> 
 Copyright 2024-25, JuliaHealth.
  </li>  
</ul>
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://github.com/JuliaHealth/JuliaHealthBlog">
<p>Report Issue</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>