---
title: "Related Organizations"
---

This is a (not necessarily comprehensive) list of organizations that focus primarily on developing and maintaining open-source Julia packages related to the life sciences and health sciences.

If you would like to add an organization to this list, please feel free to [make a pull request](https://github.com/JuliaHealth/juliahealth.github.io/blob/dev/{{fd_rpath}}).

## Julia community organizations

* [BioJulia](https://github.com/BioJulia) – Biology, bioinformatics, and computational biology ([website](https://biojulia.dev) | [Gitter](https://gitter.im/BioJulia/home))
* [EcoJulia](https://github.com/EcoJulia) - Ecology ([website](https://ecojulia.github.io))
* [JuliaHealth](https://github.com/JuliaHealth) – Medicine, health care, public health, and biomedical research ([website](https://juliahealth.org))
* [JuliaEpi](https://github.com/JuliaEpi) – Epidemiology
* [JuliaNeuro](https://github.com/JuliaNeuro) - Neuroscience ([website](https://julianeuro.github.io))
* [JuliaNeuroscience](https://github.com/JuliaNeuroscience) - Neuroscience
* [MagneticResonanceImaging](https://github.com/MagneticResonanceImaging) - Magnetic resonance imaging

## Labs and research groups

* [BCBI](https://github.com/bcbi) – Center for Biomedical Informatics at Brown University ([website](https://brown.edu/go/bcbi))
* [Holy Lab](https://github.com/HolyLab) - Holy Lab at Washington University in St. Louis ([website](http://holylab.wustl.edu/))
* [InPhyT](https://github.com/InPhyT) - Interdisciplinary Physics Team 

## Companies

* [Beacon Biosignals](https://github.com/beacon-biosignals) -  Intelligent brain monitoring technologies ([website](https://beacon.bio))
* [PumasAI](https://github.com/PumasAI) - Pharmaceutical modeling and simulation ([website](https://pumas.ai))
